kind: pipeline
name: default
steps:
  - name: ganache
    image: trufflesuite/ganache-cli:v6.4.3
    detach: true

  - name: core
    image: enigmampc/enigma-core:0.0.5-rocksdb-5.17.2
    depends_on: [clone]
    privileged: true
    commands:
      - /opt/intel/libsgx-enclave-common/aesm/aesm_service
      - . /opt/sgxsdk/environment && . /root/.cargo/env
      - cd enigma-core && RUSTFLAGS=-Awarnings make DEBUG=1
      - cd app && RUSTFLAGS=-Awarnings cargo test
    volumes:
      - name: isgx
        path: /dev/isgx

  - name: principal
    image: enigmampc/enigma-core:0.0.5-rocksdb-5.17.2
    depends_on: [clone]
    privileged: true
    commands:
      - /opt/intel/libsgx-enclave-common/aesm/aesm_service
      - . /opt/sgxsdk/environment && . /root/.cargo/env
      - export NODE_URL="http://ganache:8545"
      - cd enigma-principal && RUSTFLAGS=-Awarnings make DEBUG=1
      - cd app && RUSTFLAGS=-Awarnings cargo test
    volumes:
      - name: isgx
        path: /dev/isgx

  - name: tools_u
    image: enigmampc/enigma-core:0.0.5-rocksdb-5.17.2
    depends_on: [clone]
    commands:
      - . /root/.cargo/env
      - export NODE_URL="http://ganache:8545"
      - cd enigma-tools-u
      - RUSTFLAGS=-Awarnings cargo test

  - name: enigma_crypto
    image: enigmampc/enigma-core:0.0.5-rocksdb-5.17.2
    depends_on: [clone]
    commands:
      - . /root/.cargo/env
      - cd enigma-crypto
      - RUSTFLAGS=-Awarnings cargo test
      - RUSTFLAGS=-Awarnings cargo build --no-default-features --features=sgx

  - name: tools_m
    image: enigmampc/enigma-core:0.0.5-rocksdb-5.17.2
    depends_on: [clone]
    commands:
      - . /root/.cargo/env
      - cd enigma-tools-m
      - RUSTFLAGS=-Awarnings cargo test
      - RUSTFLAGS=-Awarnings cargo build --no-default-features --features=sgx

volumes:
  - name: isgx
    host:
      path: /dev/isgx
